# Podemos utilizar este para hacer la limpieza completa del DF, y luego lo guardamos, y es el que vamos a cargar para el análisis.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./data/listings.csv")

In [3]:
df.head(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,96033,"Bonito piso a 200m de la playa, El Palo (Málaga)",510467,Rafael,NaN,Este,36.720310,-4.356270,Entire home/apt,58.0,3,274,2025-09-29,1.88,1,324,40,ESFCTU0000290200003588210000000000000000VUT/MA...
1,166473,Perfect Location In Malaga,793360,Fred,NaN,Este,36.720310,-4.361080,Private room,28.0,5,102,2025-03-27,0.59,5,288,3,NaN
2,330760,Malaga Lodge Guesthouse Double room-shared bath.,1687526,Mayte,NaN,Centro,36.729786,-4.413462,Private room,60.0,1,68,2025-09-04,0.41,6,64,12,ESHFTU0000290200004234200060000000000000VFT/MA...
3,340024,NEW APARTMENT IN MALAGA CENTER,1725690,Carlos,NaN,Centro,36.728130,-4.414220,Entire home/apt,61.0,3,322,2025-09-09,2.11,1,297,38,VFT/MA/02334
4,358541,Casa La Maga - Apartment for happy people,1526932,Cristina,NaN,Centro,36.723740,-4.421300,Entire home/apt,87.0,2,405,2025-07-27,2.48,1,195,23,VFT/MA/02288

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9714 entries, 0 to 9713
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              9714 non-null   int64
 1   name                            9714 non-null   str
 2   host_id                         9714 non-null   int64
 3   host_name                       9714 non-null   str
 4   neighbourhood_group             0 non-null      float64
 5   neighbourhood                   9714 non-null   str
 6   latitude                        9714 non-null   float64
 7   longitude                       9714 non-null   float64
 8   room_type                       9714 non-null   str
 9   price                           8815 non-null   float64
 10  minimum_nights                  9714 non-null   int64
 11  number_of_reviews               9714 non-null   int64
 12  last_review                     8709 non-null   str
 13  reviews_per_month               8709 non-null   float64
 14  calculated_host_listings_count  9714 non-null   int64
 15  availability_365                9714 non-null   int64
 16  number_of_reviews_ltm           9714 non-null   int64
 17  license                         9587 non-null   str
dtypes: float64(5), int64(7), str(6)
memory usage: 1.3 MB

In [5]:
df.isnull().sum()

id                                   0
name                                 0
host_id                              0
host_name                            0
neighbourhood_group               9714
neighbourhood                        0
latitude                             0
longitude                            0
room_type                            0
price                              899
minimum_nights                       0
number_of_reviews                    0
last_review                       1005
reviews_per_month                 1005
calculated_host_listings_count       0
availability_365                     0
number_of_reviews_ltm                0
license                            127
dtype: int64

In [ ]:
# considero que los precios nulos y las reseñas tmb son importantes y son demasiados datos nulos en un DF,
# podemos analizar si eliminarlas directamente o ver que hacer con ellas
# reviews_per_month
# last_review
# reviews_per_month
# license nulos, hay que ver que tipo de apartamentos/habitaciones son

In [ ]:
# comprobar que las ultimas reseñas estén en el año 2025, y con esto evitamos los nulos en las columnas last_reviews y reviews_per_month. Tmb comprobamos que son 
# apartamentos/viviendas en activo.
# para ello debemos comprobar que la columna last_review es una fecha
df["last_review"] = pd.to_datetime(df["last_review"], errors="coerce")

In [7]:
# ya que hay bastantes datos en el año 2025, podríamos estudiar solo los del año 2025... 
# # de esta forma, nos aseguramos que las columnas de last_reviews y reviews_per_month no tengan nulos
df_2025 = df[df["last_review"].dt.year == 2025]

In [8]:
df_2025.info()

<class 'pandas.DataFrame'>
Index: 7338 entries, 0 to 9688
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              7338 non-null   int64
 1   name                            7338 non-null   str
 2   host_id                         7338 non-null   int64
 3   host_name                       7338 non-null   str
 4   neighbourhood_group             0 non-null      float64
 5   neighbourhood                   7338 non-null   str
 6   latitude                        7338 non-null   float64
 7   longitude                       7338 non-null   float64
 8   room_type                       7338 non-null   str
 9   price                           6861 non-null   float64
 10  minimum_nights                  7338 non-null   int64
 11  number_of_reviews               7338 non-null   int64
 12  last_review                     7338 non-null   datetime64[us]
 13  reviews_per_month               7338 non-null   float64
 14  calculated_host_listings_count  7338 non-null   int64
 15  availability_365                7338 non-null   int64
 16  number_of_reviews_ltm           7338 non-null   int64
 17  license                         7282 non-null   str
dtypes: datetime64[us](1), float64(5), int64(7), str(5)
memory usage: 1.1 MB

In [9]:
# la columna de neighbourhood_group nos la podemos cargar directamente
df_2025 = df_2025.drop(columns=["neighbourhood_group", "latitude", "longitude"])

In [10]:
df_2025.info()

<class 'pandas.DataFrame'>
Index: 7338 entries, 0 to 9688
Data columns (total 15 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              7338 non-null   int64
 1   name                            7338 non-null   str
 2   host_id                         7338 non-null   int64
 3   host_name                       7338 non-null   str
 4   neighbourhood                   7338 non-null   str
 5   room_type                       7338 non-null   str
 6   price                           6861 non-null   float64
 7   minimum_nights                  7338 non-null   int64
 8   number_of_reviews               7338 non-null   int64
 9   last_review                     7338 non-null   datetime64[us]
 10  reviews_per_month               7338 non-null   float64
 11  calculated_host_listings_count  7338 non-null   int64
 12  availability_365                7338 non-null   int64
 13  number_of_reviews_ltm           7338 non-null   int64
 14  license                         7282 non-null   str
dtypes: datetime64[us](1), float64(2), int64(7), str(5)
memory usage: 917.2 KB

In [ ]:
df_2025.duplicated().sum()
# no hay duplicados

np.int64(0)

In [16]:
df_2025.isnull().sum()

id                                  0
name                                0
host_id                             0
host_name                           0
neighbourhood                       0
room_type                           0
price                             477
minimum_nights                      0
number_of_reviews                   0
last_review                         0
reviews_per_month                   0
calculated_host_listings_count      0
availability_365                    0
number_of_reviews_ltm               0
license                            56
dtype: int64

In [22]:
# las filas de precios nulos las eliminamos presentan un porcentaje del 6.5% del total
df_2025 = df_2025.dropna(subset=["price"])

In [ ]:
df_2025.isnull().sum()

id                                 0
name                               0
host_id                            0
host_name                          0
neighbourhood                      0
room_type                          0
price                              0
minimum_nights                     0
number_of_reviews                  0
last_review                        0
reviews_per_month                  0
calculated_host_listings_count     0
availability_365                   0
number_of_reviews_ltm              0
license                           55
dtype: int64

In [ ]:
# Tenemos 55 nulos en licence (de esta podriamos analizar si los alojamientos sin licencia son mas baratos, 
    # o tienen mayor disponibilidad)

In [27]:
df_2025["neighbourhood"].value_counts()

neighbourhood
Centro                  4615
Este                     689
Carretera de Cadiz       666
Cruz De Humilladero      294
Bailen-Miraflores        217
Palma-Palmilla           123
Churriana                110
Ciudad Jardin             52
Teatinos-Universidad      47
Puerto de la Torre        29
Campanillas               19
Name: count, dtype: int64

In [29]:
df_2025["room_type"].value_counts()

room_type
Entire home/apt    6116
Private room        731
Shared room          13
Hotel room            1
Name: count, dtype: int64

In [28]:
df_2025[df_2025["license"].isnull()]["room_type"].value_counts()

room_type
Entire home/apt    45
Private room       10
Name: count, dtype: int64

In [33]:
cardinalidades = {}
for column in df_2025:
    cardinalidad = len(df_2025[column].unique())/len(df_2025)*100
    cardinalidades[column] = round(cardinalidad, 2)
    print(f"La cardinalidad de la columna {column} es de {cardinalidad:.2f}")
    
cardinalidades

La cardinalidad de la columna id es de 100.00
La cardinalidad de la columna name es de 97.90
La cardinalidad de la columna host_id es de 38.59
La cardinalidad de la columna host_name es de 19.94
La cardinalidad de la columna neighbourhood es de 0.16
La cardinalidad de la columna room_type es de 0.06
La cardinalidad de la columna price es de 6.47
La cardinalidad de la columna minimum_nights es de 0.42
La cardinalidad de la columna number_of_reviews es de 6.49
La cardinalidad de la columna last_review es de 3.83
La cardinalidad de la columna reviews_per_month es de 9.58
La cardinalidad de la columna calculated_host_listings_count es de 0.82
La cardinalidad de la columna availability_365 es de 5.33
La cardinalidad de la columna number_of_reviews_ltm es de 1.76
La cardinalidad de la columna license es de 80.00

{'id': 100.0,
 'name': 97.9,
 'host_id': 38.59,
 'host_name': 19.94,
 'neighbourhood': 0.16,
 'room_type': 0.06,
 'price': 6.47,
 'minimum_nights': 0.42,
 'number_of_reviews': 6.49,
 'last_review': 3.83,
 'reviews_per_month': 9.58,
 'calculated_host_listings_count': 0.82,
 'availability_365': 5.33,
 'number_of_reviews_ltm': 1.76,
 'license': 80.0}

In [34]:
# pasamos la columna id a índice ya que tiene una cardinalidad del 100%
df_2025.set_index("id", inplace=True)

In [35]:
df_2025.head(2)

,name,host_id,host_name,neighbourhood,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
id,,,,,,,,,,,,,,
96033,"Bonito piso a 200m de la playa, El Palo (Málaga)",510467,Rafael,Este,Entire home/apt,58.0,3,274,2025-09-29,1.88,1,324,40,ESFCTU0000290200003588210000000000000000VUT/MA...
166473,Perfect Location In Malaga,793360,Fred,Este,Private room,28.0,5,102,2025-03-27,0.59,5,288,3,NaN

In [36]:
def cardinalidad(df_in, umbral_categoria, umbral_continua):

    resultados = []

    for col in df_in.columns:
        # Cardinalidad absoluta
        card = df_in[col].nunique(dropna=True)

        # Porcentaje de cardinalidad
        pct = card / len(df_in) * 100

        # Clasificación según reglas
        if card == 2:
            tipo = "Binaria"
        elif card < umbral_categoria:
            tipo = "Categorica"
        else:
            if pct >= umbral_continua:
                tipo = "Numerica Continua"
            else:
                tipo = "Numerica Discreta"

        # 👉 Guardamos el resultado de esta columna
        resultados.append({
            "columna": col,
            "cardinalidad": card,
            "pct_cardinalidad": pct,
            "tipo": tipo
        })

    return pd.DataFrame(resultados)

In [38]:
cardinalidad(df_2025, 12, 0.3)

,columna,cardinalidad,pct_cardinalidad,tipo
0,name,6717,97.901181,Numerica Continua
1,host_id,2648,38.594957,Numerica Continua
2,host_name,1368,19.938784,Numerica Continua
3,neighbourhood,11,0.160326,Categorica
4,room_type,4,0.058301,Categorica
5,price,444,6.471360,Numerica Continua
6,minimum_nights,29,0.422679,Numerica Continua
7,number_of_reviews,445,6.485935,Numerica Continua
8,last_review,263,3.833260,Numerica Continua
9,reviews_per_month,657,9.575864,Numerica Continua
10,calculated_host_listings_count,56,0.816208,Numerica Continua
11,availability_365,366,5.334499,Numerica Continua
12,number_of_reviews_ltm,121,1.763591,Numerica Continua
13,license,5488,79.988340,Numerica Continua

In [39]:
def cardinalidad(df_in, umbral_categoria, umbral_continua):

    resultados = []

    for col in df_in.columns:
        serie = df_in[col]

        # 1. Tipo de dato
        if serie.dtype == "object":
            tipo = "Categorica"
        elif "datetime" in str(serie.dtype):
            tipo = "Fecha"
        else:
            # 2. Reglas de cardinalidad solo para numéricas
            card = serie.nunique(dropna=True)
            pct = card / len(df_in) * 100

            if card == 2:
                tipo = "Binaria"
            elif card < umbral_categoria:
                tipo = "Categorica"
            else:
                tipo = "Numerica Continua" if pct >= umbral_continua else "Numerica Discreta"

        resultados.append({
            "columna": col,
            "tipo": tipo
        })

    return pd.DataFrame(resultados)

In [40]:
cardinalidad(df_2025, 12, 0.3)

                           columna               tipo
0                             name  Numerica Continua
1                          host_id  Numerica Continua
2                        host_name  Numerica Continua
3                    neighbourhood         Categorica
4                        room_type         Categorica
5                            price  Numerica Continua
6                   minimum_nights  Numerica Continua
7                number_of_reviews  Numerica Continua
8                      last_review              Fecha
9                reviews_per_month  Numerica Continua
10  calculated_host_listings_count  Numerica Continua
11                availability_365  Numerica Continua
12           number_of_reviews_ltm  Numerica Continua
13                         license  Numerica Continua

In [31]:
df_2025.head(2)

,id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,96033,"Bonito piso a 200m de la playa, El Palo (Málaga)",510467,Rafael,Este,36.72031,-4.35627,Entire home/apt,58.0,3,274,2025-09-29,1.88,1,324,40,ESFCTU0000290200003588210000000000000000VUT/MA...
1,166473,Perfect Location In Malaga,793360,Fred,Este,36.72031,-4.36108,Private room,28.0,5,102,2025-03-27,0.59,5,288,3,NaN

In [ ]:
|**Columna/Variable** | **Tipo de Variable** |**Descripción** |
|---------------------|-----------------|------------------|
| id | |

In [41]:

df_2025.to_csv("df_2025_limpio.csv", index=False)